import { createElement } from 'lwc';
import Recap02CreateAccountNoClass from 'c/recap02CreateAccountNoClass';

describe('c-recap02-create-account-no-class', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-recap02-create-account-no-class', {
            is: Recap02CreateAccountNoClass
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});